language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --dev

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit -c phpunit.xml.dist --verbose